import type { CuratedProductSeed } from './supplement-catalog';

/**
 * Shopify-sourced product seeds covering every catalog supplement that does
 * not have a hand-curated merchant listing. Each entry carries a live Shopify
 * product + variant ID verified against the merchant storefront, so every
 * supplement page can offer a working cart-permalink checkout.
 *
 * Regenerate with: node src/scripts/sourceShopifyProducts.mjs
 * Validate with:   npm run verify:shopify-catalog
 */
export const sourcedProductSeeds: CuratedProductSeed[] = [
  {
    product_id: 'real-piping-rock-vitamin-d3',
    product_name: 'Vitamin D3, 5000 IU, 120 Quick Release Softgels',
    product_description:
      'Piping Rock vitamin d3 pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 5.7,
    product_url: 'https://www.pipingrock.com/products/vitamin-d3-5000-iu-120-quick-release-softgels-21310',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0640/7323/6718/files/vitamin-d3-5000-iu-120-quick-release-softgels-21310.jpg?v=1782340676',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'piping-rock',
    brands: { brand_name: 'Piping Rock' },
    supplement_name: 'Vitamin D3',
    shopify_product_gid: 'gid://shopify/Product/7782060196078',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43261475684590',
    shopify_store_domain: 'www.pipingrock.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-bulksupplements-vitamin-k2',
    product_name: 'Vitamin K2 MK7 Powder',
    product_description:
      'BulkSupplements vitamin k2 pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 18.97,
    product_url: 'https://bulksupplements.com/products/vitamin-k2-mk7',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0114/8869/0276/files/Vitamin-K2-MK7-10g-Main-Image-V003.jpg?v=1780432581',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'bulksupplements',
    brands: { brand_name: 'BulkSupplements' },
    supplement_name: 'Vitamin K2',
    shopify_product_gid: 'gid://shopify/Product/4378705297519',
    shopify_variant_gid: 'gid://shopify/ProductVariant/32133365792879',
    shopify_store_domain: 'bulksupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-piping-rock-vitamin-c',
    product_name: 'Chewable Vitamin C (Natural Orange), 1000 mg (per serving), 180 Chewable Tablets',
    product_description:
      'Piping Rock vitamin c pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 9.89,
    product_url: 'https://www.pipingrock.com/products/chewable-vitamin-c-natural-orange-1000-mg-per-serving-180-chewable-tablets-5537',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0640/7323/6718/files/chewable-vitamin-c-natural-orange-1000-mg-per-serving-180-chewable-tablets-5537.jpg?v=1782342881',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'piping-rock',
    brands: { brand_name: 'Piping Rock' },
    supplement_name: 'Vitamin C',
    shopify_product_gid: 'gid://shopify/Product/7782065242350',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43261481582830',
    shopify_store_domain: 'www.pipingrock.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Tablets'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-vitamin-b12',
    product_name: 'Nutricost Vitamin B12 Capsules',
    product_description:
      'Nutricost vitamin b12 pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 11.97,
    product_url: 'https://nutricost.com/products/nutricost-vitamin-b12-2000mcg-240-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_VitaminB12_1MG__V1__240CAPS_275CC_Front1_Square_61b8f3f5-7ae9-453e-b08d-172aa7c8fe0d.jpg?v=1768597251',
    servings_per_container: 12,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Vitamin B12',
    shopify_product_gid: 'gid://shopify/Product/3702314270794',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43159387832550',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-b-complex',
    product_name: 'Nutricost Vitamin B Complex Capsules',
    product_description:
      'Nutricost b-complex pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 16.97,
    product_url: 'https://nutricost.com/products/nutricost-vitamin-b-complex-747mg-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_VitaminBComplex_460MG__V00__30CAP_150CC_Front1_Square.jpg?v=1752248502',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'B-Complex',
    shopify_product_gid: 'gid://shopify/Product/3699323568202',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28718944387146',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-folate',
    product_name: 'Nutricost Methyl Folate Capsules',
    product_description:
      'Nutricost folate pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 14.97,
    product_url: 'https://nutricost.com/products/nutricost-methyl-folate-capsules-1000mg-120-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/products/nutricost-methyl-folate-capsules-864373.jpg?v=1709213296',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Folate',
    shopify_product_gid: 'gid://shopify/Product/3729181179978',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28978948046922',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-biotin',
    product_name: 'Nutricost Biotin Capsules',
    product_description:
      'Nutricost biotin pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 11.97,
    product_url: 'https://nutricost.com/products/nutricost-biotin-10mg-240-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Biotin_10MG_120CAP_Front_916bdcb2-ea91-4127-9fea-366ffe8576a6.jpg?v=1728668223',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Biotin',
    shopify_product_gid: 'gid://shopify/Product/3702140108874',
    shopify_variant_gid: 'gid://shopify/ProductVariant/45419128258790',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-magnesium-glycinate',
    product_name: 'Nutricost Magnesium Glycinate Powder',
    product_description:
      'Nutricost magnesium glycinate pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 21.97,
    product_url: 'https://nutricost.com/products/nutricost-magnesium-glycinate-powder-250-grams',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Magnesium_Glycinate_UF_250_GM_16_OZ_Front_Square.jpg?v=1754587806',
    servings_per_container: 135,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Magnesium Glycinate',
    shopify_product_gid: 'gid://shopify/Product/3699296731210',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28718821670986',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-magnesium-citrate',
    product_name: 'Nutricost Magnesium Citrate Capsules',
    product_description:
      'Nutricost magnesium citrate pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 13.97,
    product_url: 'https://nutricost.com/products/nutricost-magnesium-citrate-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_MagnesiumCitrate_150MGX4_60CAP_175CC_Front_Square.jpg?v=1753374597',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Magnesium Citrate',
    shopify_product_gid: 'gid://shopify/Product/4786668306506',
    shopify_variant_gid: 'gid://shopify/ProductVariant/32510923964490',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-zinc',
    product_name: 'Nutricost Zinc Picolinate Capsules',
    product_description:
      'Nutricost zinc pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 16.97,
    product_url: 'https://nutricost.com/products/nutricost-zinc-picolinate-50mg-240-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_ZincPicolinate_50MG_120CAP_175CC_Front_Square.jpg?v=1768514671',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Zinc',
    shopify_product_gid: 'gid://shopify/Product/3702318399562',
    shopify_variant_gid: 'gid://shopify/ProductVariant/32344195268682',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-iron',
    product_name: 'Nutricost Iron Bisglycinate',
    product_description:
      'Nutricost iron pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 11.97,
    product_url: 'https://nutricost.com/products/nutricost-iron-bisglycinate',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_IronBisglycinate_25MG_240CAPS_275CC_Front1_Square.jpg?v=1745440127',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Iron',
    shopify_product_gid: 'gid://shopify/Product/8459568185574',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44349064773862',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-calcium',
    product_name: 'Nutricost Calcium Citrate Powder',
    product_description:
      'Nutricost calcium pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 13.97,
    product_url: 'https://nutricost.com/products/nutricost-calcium-citrate-powder-250-grams',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/products/nutricost-calcium-citrate-powder-569191.jpg?v=1689400081',
    servings_per_container: 147,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Calcium',
    shopify_product_gid: 'gid://shopify/Product/3699305152586',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28718860828746',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-selenium',
    product_name: 'Nutricost Selenium Capsules',
    product_description:
      'Nutricost selenium pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 14.97,
    product_url: 'https://nutricost.com/products/nutricost-selenium-200mcg-240-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Selenium_200MCG_240CAP_275CC_Front_Square.jpg?v=1744820135',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Selenium',
    shopify_product_gid: 'gid://shopify/Product/3702313779274',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43159460020454',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-iodine',
    product_name: 'Nutricost Iodine Tablets',
    product_description:
      'Nutricost iodine pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 13.97,
    product_url: 'https://nutricost.com/products/nutricost-iodine-240-tablets',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Iodine_240TBL_150CCCOMPAX_Front_Square.jpg?v=1773430729',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Iodine',
    shopify_product_gid: 'gid://shopify/Product/6774197420225',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40129604190401',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Tablets'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-omega-3-fish-oil',
    product_name: 'Nutricost Fish Oil Softgels',
    product_description:
      'Nutricost omega-3 fish oil pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 30.97,
    product_url: 'https://nutricost.com/products/nutricost-fish-oil-1000mg-240-softgels',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_FishOil_1000mg_240SFG_750CC_Front_Square.jpg?v=1751920237',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Omega-3 Fish Oil',
    shopify_product_gid: 'gid://shopify/Product/3703024451658',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28765022879818',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-krill-oil',
    product_name: 'Nutricost Krill Oil Complex Softgels',
    product_description:
      'Nutricost krill oil pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 24.97,
    product_url: 'https://nutricost.com/products/nutricost-krill-oil-complex-softgels',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_KrillOil_500MG__Superba__60SFG_150CCCOMPAX_Front1_Square.jpg?v=1757953800',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Krill Oil',
    shopify_product_gid: 'gid://shopify/Product/8119796924646',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43627710152934',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-micro-ingredients-algal-oil',
    product_name: 'Micro Ingredients Vegan Omega 3 Algae Oil Supplement 1,250 mg Per Serving',
    product_description:
      'Micro Ingredients algal oil pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 26.99,
    product_url: 'https://microingredients.com/products/micro-ingredients-vegan-omega-3-algae-oil-supplement-1-250-mg-per-serving',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/1866/1287/files/Product-Shopify_0a0b0de8-6ac2-4aef-9c17-d0d7c94e2ebd.png?v=1772583289',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'micro-ingredients',
    brands: { brand_name: 'Micro Ingredients' },
    supplement_name: 'Algal Oil',
    shopify_product_gid: 'gid://shopify/Product/8666624098531',
    shopify_variant_gid: 'gid://shopify/ProductVariant/45543065649379',
    shopify_store_domain: 'microingredients.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Liquid'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-cod-liver-oil',
    product_name: 'Nutricost Cod Liver Oil',
    product_description:
      'Nutricost cod liver oil pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 17.97,
    product_url: 'https://nutricost.com/products/nutricost-cod-liver-oil',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_CodLiverOil_120SFG_1000MG_Front.jpg?v=1695320532',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Cod Liver Oil',
    shopify_product_gid: 'gid://shopify/Product/8177596367078',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43718962938086',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Liquid'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-double-wood-collagen-peptides',
    product_name: 'Collagen Peptides Powder',
    product_description:
      'Double Wood Supplements collagen peptides pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 24.95,
    product_url: 'https://doublewoodsupplements.com/products/collagen-peptides',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0756/3867/files/0001_91NyvVl9aOL._AC_SL1500.jpg?v=1767120505',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'double-wood',
    brands: { brand_name: 'Double Wood Supplements' },
    supplement_name: 'Collagen Peptides',
    shopify_product_gid: 'gid://shopify/Product/5367333224601',
    shopify_variant_gid: 'gid://shopify/ProductVariant/34959555330201',
    shopify_store_domain: 'doublewoodsupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-beetroot',
    product_name: 'Nutricost Organic Beet Root Powder',
    product_description:
      'Nutricost beetroot pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 24.97,
    product_url: 'https://nutricost.com/products/nutricost-organic-beet-root-powder-1lb',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_OrganicBeetRootPowder_1LB_43OZ_Front_Square.jpg?v=1745337244',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Beetroot',
    shopify_product_gid: 'gid://shopify/Product/4781765296202',
    shopify_variant_gid: 'gid://shopify/ProductVariant/32504120377418',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-ashwagandha',
    product_name: 'Nutricost Ashwagandha Root Extract Capsules',
    product_description:
      'Nutricost ashwagandha pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 16.97,
    product_url: 'https://nutricost.com/products/nutricost-ashwagandha-root-600mg-120-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Ashwagandha_600MG_120CAP_275CC_Front_Square.jpg?v=1751918765',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Ashwagandha',
    shopify_product_gid: 'gid://shopify/Product/3702120677450',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28758178299978',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-rhodiola-rosea',
    product_name: 'Nutricost Rhodiola Rosea Capsules',
    product_description:
      'Nutricost rhodiola rosea pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 19.97,
    product_url: 'https://nutricost.com/products/nutricost-rhodiola-rosea-500mg-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_RhodiolaRosea_500MG_60CAP_150CC_Front.jpg?v=1697664966',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Rhodiola Rosea',
    shopify_product_gid: 'gid://shopify/Product/3702330196042',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28759511236682',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-panax-ginseng',
    product_name: 'Nutricost Panax Ginseng Capsules',
    product_description:
      'Nutricost panax ginseng pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 18.97,
    product_url: 'https://nutricost.com/products/nutricost-panax-ginseng-500mg-240-capsules-1',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_PanaxGinseng_500MG_240CAP_400CC_Front_Square.jpg?v=1775842231',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Panax Ginseng',
    shopify_product_gid: 'gid://shopify/Product/3712231440458',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28860531212362',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-maca-root',
    product_name: 'Nutricost Maca Root Capsules',
    product_description:
      'Nutricost maca root pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 17.97,
    product_url: 'https://nutricost.com/products/nutricost-maca-root-750mg-180-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/products/nutricost-maca-root-capsules-547322.jpg?v=1687483091',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Maca Root',
    shopify_product_gid: 'gid://shopify/Product/3702363717706',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28759775019082',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-micro-ingredients-turmeric-curcumin',
    product_name: 'Micro Ingredients Turmeric Curcumin 1,000mg',
    product_description:
      'Micro Ingredients turmeric curcumin pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 26.95,
    product_url: 'https://microingredients.com/products/micro-ingredients-pure-turmeric-curcumin-supplement-1-000mg-95-curcuminoids',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/1866/1287/files/Product-Shopify_02b88450-976a-42d2-9c0c-330ce8b57d5d.png?v=1772574481',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'micro-ingredients',
    brands: { brand_name: 'Micro Ingredients' },
    supplement_name: 'Turmeric Curcumin',
    shopify_product_gid: 'gid://shopify/Product/8804225024227',
    shopify_variant_gid: 'gid://shopify/ProductVariant/46172701425891',
    shopify_store_domain: 'microingredients.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Liquid'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-ginger',
    product_name: 'Nutricost Ginger Root Extract Capsules',
    product_description:
      'Nutricost ginger pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 19.97,
    product_url: 'https://nutricost.com/products/nutricost-ginger-root-extract-550mg-240-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_GingerRoot_550MG_240CAP_500CC_Front_Square.jpg?v=1783031875',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Ginger',
    shopify_product_gid: 'gid://shopify/Product/3702309290058',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28759377543242',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-micro-ingredients-garlic-extract',
    product_name: 'Micro Ingredients Odorless Aged Garlic Extract Softgels',
    product_description:
      'Micro Ingredients garlic extract pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 29.95,
    product_url: 'https://microingredients.com/products/odorless-garlic-softgels',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/1866/1287/files/AgedGarlicExtract_Artboard1copy36-07_3ce078ab-24df-43d8-b6ca-14698b5c3233.jpg?v=1776702361',
    servings_per_container: 300,
    servings_per_day: 1,
    brand_id: 'micro-ingredients',
    brands: { brand_name: 'Micro Ingredients' },
    supplement_name: 'Garlic Extract',
    shopify_product_gid: 'gid://shopify/Product/4601679380613',
    shopify_variant_gid: 'gid://shopify/ProductVariant/48425150742755',
    shopify_store_domain: 'microingredients.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-milk-thistle',
    product_name: 'Nutricost Milk Thistle Capsules',
    product_description:
      'Nutricost milk thistle pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 15.97,
    product_url: 'https://nutricost.com/products/nutricost-milk-thistle-250mg-240-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_MilkThistle_250MG__V1__240CAP_275CC_Front1_Square.jpg?v=1775840290',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Milk Thistle',
    shopify_product_gid: 'gid://shopify/Product/3702313091146',
    shopify_variant_gid: 'gid://shopify/ProductVariant/45477938659558',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-holy-basil',
    product_name: 'Nutricost Holy Basil Capsules',
    product_description:
      'Nutricost holy basil pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 14.97,
    product_url: 'https://nutricost.com/products/nutricost-holy-basil-500mg-120-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_HolyBasil_500MG_120CAP_225CC_Front_Square.jpg?v=1775836125',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Holy Basil',
    shopify_product_gid: 'gid://shopify/Product/3810972631114',
    shopify_variant_gid: 'gid://shopify/ProductVariant/29360766287946',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-bacopa-monnieri',
    product_name: 'Nutricost Bacopa Monnieri',
    product_description:
      'Nutricost bacopa monnieri pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 18.97,
    product_url: 'https://nutricost.com/products/nutricost-bacopa-monnieri',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_BacopaMonnieri_500MG_120CAP_275CC_Front_Square.jpg?v=1775680375',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Bacopa Monnieri',
    shopify_product_gid: 'gid://shopify/Product/6881372995777',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40562214633665',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-ginkgo-biloba',
    product_name: 'Nutricost Ginkgo Biloba Capsules',
    product_description:
      'Nutricost ginkgo biloba pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 16.97,
    product_url: 'https://nutricost.com/products/nutricost-ginkgo-biloba-120mg-240-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_GinkoBilboa_120MG_240CAP_400CC_Front_Square.jpg?v=1775832199',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Ginkgo Biloba',
    shopify_product_gid: 'gid://shopify/Product/3702310142026',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28759381639242',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-micro-ingredients-lion-s-mane-mushroom',
    product_name: 'Micro Ingredients Organic Lions Mane Mushroom Supplement Powder',
    product_description:
      'Micro Ingredients lion\'s mane mushroom pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 38.95,
    product_url: 'https://microingredients.com/products/organic-lions-mane-mushroom-powder',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/1866/1287/files/Lionsmaneweb1.jpg?v=1770931129',
    servings_per_container: 302,
    servings_per_day: 1,
    brand_id: 'micro-ingredients',
    brands: { brand_name: 'Micro Ingredients' },
    supplement_name: 'Lion\'s Mane Mushroom',
    shopify_product_gid: 'gid://shopify/Product/4603381743749',
    shopify_variant_gid: 'gid://shopify/ProductVariant/45887957467363',
    shopify_store_domain: 'microingredients.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-alpha-gpc',
    product_name: 'Nutricost Alpha GPC Capsules',
    product_description:
      'Nutricost alpha-gpc pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 27.97,
    product_url: 'https://nutricost.com/products/nutricost-alpha-gpc-300mg',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_AlphaGPC_300mgX2_120CAP_225CC_Front_Square_1.jpg?v=1773419705',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Alpha-GPC',
    shopify_product_gid: 'gid://shopify/Product/3695162654794',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28695877845066',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-cdp-choline',
    product_name: 'Nutricost Cognizin Citicoline',
    product_description:
      'Nutricost cdp-choline pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 38.97,
    product_url: 'https://nutricost.com/products/nutricost-cognizin-citicoline',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Cognizin_500MGX2_60CAP_175CC_Front_Square.jpg?v=1778882817',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'CDP-Choline',
    shopify_product_gid: 'gid://shopify/Product/9723063828710',
    shopify_variant_gid: 'gid://shopify/ProductVariant/47671264051430',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-double-wood-phosphatidylserine',
    product_name: 'Phosphatidylserine Supplement',
    product_description:
      'Double Wood Supplements phosphatidylserine pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 22.95,
    product_url: 'https://doublewoodsupplements.com/products/phosphatidylserine',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0756/3867/files/Phosphatidylserine_Front_5hcym4_0a86b6fa-7075-4446-b9f8-e1fe32aeeff0.jpg?v=1767120064',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'double-wood',
    brands: { brand_name: 'Double Wood Supplements' },
    supplement_name: 'Phosphatidylserine',
    shopify_product_gid: 'gid://shopify/Product/644875550747',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44435936510146',
    shopify_store_domain: 'doublewoodsupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-l-theanine',
    product_name: 'Nutricost L-Theanine Capsules',
    product_description:
      'Nutricost l-theanine pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 13.97,
    product_url: 'https://nutricost.com/products/nutricost-l-theanine-200mg-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_LTheanine_200MG_30CAP_Front1.jpg?v=1735853218',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'L-Theanine',
    shopify_product_gid: 'gid://shopify/Product/3699322060874',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28718937735242',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-glycine',
    product_name: 'Nutricost Glycine Powder',
    product_description:
      'Nutricost glycine pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 24.97,
    product_url: 'https://nutricost.com/products/nutricost-glycine-powder',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Glycine_1LBS_20OZ_Front1_Square.jpg?v=1781906540',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Glycine',
    shopify_product_gid: 'gid://shopify/Product/6919350288577',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40696459428033',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-l-tyrosine',
    product_name: 'Nutricost L-Tyrosine Capsules',
    product_description:
      'Nutricost l-tyrosine pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 16.97,
    product_url: 'https://nutricost.com/products/nutricost-l-tyrosine-500mg-180-capsules-1',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_L-Tyrosine_500MG_180CAP_400CC_Front1_Square.jpg?v=1752016590',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'L-Tyrosine',
    shopify_product_gid: 'gid://shopify/Product/3716063789130',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28884269236298',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-nac',
    product_name: 'Nutricost N-Acetyl L-Cysteine (NAC) Capsules',
    product_description:
      'Nutricost nac pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 14.97,
    product_url: 'https://nutricost.com/products/nutricost-n-acetyl-l-cysteine-nac-600mg',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_N-AcetylL-Cysteine_NAC_Vegan_600MG_30CAP_100CC_Front1_Square.jpg?v=1768519133',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'NAC',
    shopify_product_gid: 'gid://shopify/Product/3695219048522',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43615277613286',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-l-carnitine',
    product_name: 'Nutricost L-Carnitine Tartrate Capsules',
    product_description:
      'Nutricost l-carnitine pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 16.97,
    product_url: 'https://nutricost.com/products/nutricost-l-carnitine-tartrate-500mg-240-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_L-CarnitneTartrate_500MGX2_120CAP_275CC_Front_Sqaure.jpg?v=1768583926',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'L-Carnitine',
    shopify_product_gid: 'gid://shopify/Product/3700442464330',
    shopify_variant_gid: 'gid://shopify/ProductVariant/32086283845706',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-gaba',
    product_name: 'Nutricost GABA',
    product_description:
      'Nutricost gaba pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 21.97,
    product_url: 'https://nutricost.com/products/nutricost-gaba',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_GABA_750MG_240CAP_500CC_Front_Square_767384fe-e045-42eb-b90b-37574e13307b.jpg?v=1775832123',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'GABA',
    shopify_product_gid: 'gid://shopify/Product/6885923160257',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40580571201729',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-melatonin',
    product_name: 'Nutricost Melatonin Tablets',
    product_description:
      'Nutricost melatonin pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 11.97,
    product_url: 'https://nutricost.com/products/nutricost-melatonin-3mg-240-caps',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Melatonin_12MG_240TABS_Front_Square.jpg?v=1736451307',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Melatonin',
    shopify_product_gid: 'gid://shopify/Product/6722586247361',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40129845002433',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Tablets'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-apigenin',
    product_name: 'Nutricost Apigenin',
    product_description:
      'Nutricost apigenin pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 24.97,
    product_url: 'https://nutricost.com/products/nutricost-apigenin',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Apigenin_50MG_180CAP_225CC_Front_Square_Square.jpg?v=1773076889',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Apigenin',
    shopify_product_gid: 'gid://shopify/Product/8436451639526',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44289206616294',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-valerian-root',
    product_name: 'Nutricost Valerian Root Capsules',
    product_description:
      'Nutricost valerian root pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 13.97,
    product_url: 'https://nutricost.com/products/nutricost-valerian-root-500mg-120-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_ValerianRoot_4000MG_120CAP_Front.jpg?v=1700512006',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Valerian Root',
    shopify_product_gid: 'gid://shopify/Product/3700438433866',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28742651248714',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-passionflower',
    product_name: 'Nutricost Passion Flower Extract',
    product_description:
      'Nutricost passionflower pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 11.97,
    product_url: 'https://nutricost.com/products/nutricost-passion-flower-extract',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_PassionFlowerExtract_375MG_120CAP_275CC_Front_Square.jpg?v=1779826991',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Passionflower',
    shopify_product_gid: 'gid://shopify/Product/7551968575718',
    shopify_variant_gid: 'gid://shopify/ProductVariant/42309638652134',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-lemon-balm',
    product_name: 'Nutricost Lemon Balm',
    product_description:
      'Nutricost lemon balm pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 11.97,
    product_url: 'https://nutricost.com/products/nutricost-lemon-balm',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_LemonBalm__10_1__150MGX2__V1__120CAP_175CC_Front1_Square.jpg?v=1751995431',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Lemon Balm',
    shopify_product_gid: 'gid://shopify/Product/9356518162662',
    shopify_variant_gid: 'gid://shopify/ProductVariant/46428351398118',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-probiotics',
    product_name: 'Nutricost Probiotic Complex Capsules',
    product_description:
      'Nutricost probiotics pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 11.97,
    product_url: 'https://nutricost.com/products/nutricost-probiotic-complex-50-billion-cfu-60-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_ProbioticComplex_10_Billion_60CAP_150CCFront.jpg?v=1724779677',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Probiotics',
    shopify_product_gid: 'gid://shopify/Product/3703027204170',
    shopify_variant_gid: 'gid://shopify/ProductVariant/45477856903398',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-prebiotic-fiber',
    product_name: 'Nutricost Organic Inulin Powder',
    product_description:
      'Nutricost prebiotic fiber pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 24.97,
    product_url: 'https://nutricost.com/products/nutricost-organic-inulin-powder',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/products/nutricost-organic-inulin-powder-352878.jpg?v=1690394541',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Prebiotic Fiber',
    shopify_product_gid: 'gid://shopify/Product/6190900183233',
    shopify_variant_gid: 'gid://shopify/ProductVariant/37877366685889',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-psyllium-husk',
    product_name: 'Nutricost Psyllium Husk (Ground) Powder',
    product_description:
      'Nutricost psyllium husk pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 21.97,
    product_url: 'https://nutricost.com/products/nutricost-psyllium-husk-ground-powder-1-lb',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_PsylliumHusk_1.5LB_44OZ_Front_Square.jpg?v=1775843627',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Psyllium Husk',
    shopify_product_gid: 'gid://shopify/Product/3702420045898',
    shopify_variant_gid: 'gid://shopify/ProductVariant/45588531544294',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-double-wood-digestive-enzymes',
    product_name: 'Digestive Enzymes Supplement',
    product_description:
      'Double Wood Supplements digestive enzymes pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 19.95,
    product_url: 'https://doublewoodsupplements.com/products/digestive-enzymes',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0756/3867/files/DigestiveEnzymes_Front_961a7947-fe51-42fb-a3eb-67f94af8806f.jpg?v=1767120909',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'double-wood',
    brands: { brand_name: 'Double Wood Supplements' },
    supplement_name: 'Digestive Enzymes',
    shopify_product_gid: 'gid://shopify/Product/6781877289154',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44434684281026',
    shopify_store_domain: 'doublewoodsupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-apple-cider-vinegar',
    product_name: 'Nutricost Apple Cider Vinegar Capsules',
    product_description:
      'Nutricost apple cider vinegar pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 11.97,
    product_url: 'https://nutricost.com/products/nutricost-apple-cider-vinegar-500mg-240-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_AppleCiderVinegar_625MGX4_120CAP_275CC_Front_Square.jpg?v=1751060500',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Apple Cider Vinegar',
    shopify_product_gid: 'gid://shopify/Product/3700439613514',
    shopify_variant_gid: 'gid://shopify/ProductVariant/46131914997990',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-berberine',
    product_name: 'Nutricost Berberine Capsules',
    product_description:
      'Nutricost berberine pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 20.97,
    product_url: 'https://nutricost.com/products/nutricost-berberine-hci-600mg-60-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_BerberineHCL_1200MG_60CAP_175CC_Front_Square.jpg?v=1738091804',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Berberine',
    shopify_product_gid: 'gid://shopify/Product/3702345826378',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28759567171658',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-chromium',
    product_name: 'Nutricost Chromium Picolinate Tablets',
    product_description:
      'Nutricost chromium pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 11.97,
    product_url: 'https://nutricost.com/products/nutricost-chromium-picolinate-tablets',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_ChromiumPicolinate_1_000MCG_240TAB_150CC_SuppFacts.jpg?v=1761679435',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Chromium',
    shopify_product_gid: 'gid://shopify/Product/7986878873830',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43391729533158',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Tablets'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-cinnamon-extract',
    product_name: 'Nutricost Organic Ceylon Cinnamon Powder',
    product_description:
      'Nutricost cinnamon extract pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 35.97,
    product_url: 'https://nutricost.com/products/nutricost-organic-ceylon-cinnamon-powder',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_OrganicCeylonCinnamon_2LB_2000CC_Front_Square.jpg?v=1735327513',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Cinnamon Extract',
    shopify_product_gid: 'gid://shopify/Product/8909822951654',
    shopify_variant_gid: 'gid://shopify/ProductVariant/45588607172838',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-myo-inositol',
    product_name: 'Nutricost Myo & D-Chiro Inositol for Women',
    product_description:
      'Nutricost myo-inositol pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 16.97,
    product_url: 'https://nutricost.com/products/nutricost-myo-d-chiro-inositol-for-women',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Myo_DChiroInositolforWomen__500MG_12.5MGX4__120CAP_225CC_Front.jpg?v=1731520296',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Myo-Inositol',
    shopify_product_gid: 'gid://shopify/Product/8049792057574',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43515537883366',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-coq10',
    product_name: 'Nutricost CoQ10 Capsules',
    product_description:
      'Nutricost coq10 pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 15.97,
    product_url: 'https://nutricost.com/products/nutricost-coq10-100mg-120-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/products/nutricost-coq10-capsules-939713.jpg?v=1687483036',
    servings_per_container: 10,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'CoQ10',
    shopify_product_gid: 'gid://shopify/Product/3702373253194',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40604196962497',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-nattokinase',
    product_name: 'Nutricost Nattokinase',
    product_description:
      'Nutricost nattokinase pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 16.97,
    product_url: 'https://nutricost.com/products/nutricost-nattokinase-2-000fu-120-caps',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Nattokinase_100MG_120CAP_175CC_Front_Square.jpg?v=1751917930',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Nattokinase',
    shopify_product_gid: 'gid://shopify/Product/7483718009062',
    shopify_variant_gid: 'gid://shopify/ProductVariant/47582185128166',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-resveratrol',
    product_name: 'Nutricost Resveratrol Capsules',
    product_description:
      'Nutricost resveratrol pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 24.97,
    product_url: 'https://nutricost.com/products/nutricost-resveratrol-500mg-120-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Resveratrol_700MGX2_120CAP_275CC_Front_Square.jpg?v=1744133472',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Resveratrol',
    shopify_product_gid: 'gid://shopify/Product/3700437680202',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28742639255626',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-nmn',
    product_name: 'Nutricost NMN',
    product_description:
      'Nutricost nmn pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 21.97,
    product_url: 'https://nutricost.com/products/nutricost-nmn',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_NMN_250MGX2_60CAP_150CCCOMPAX_Front_Square.jpg?v=1775841415',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'NMN',
    shopify_product_gid: 'gid://shopify/Product/8059119304934',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43534893220070',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-bulksupplements-nr',
    product_name: 'Nicotinamide Riboside Capsules',
    product_description:
      'BulkSupplements nr pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 27.97,
    product_url: 'https://bulksupplements.com/products/nicotinamide-riboside-pills',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0114/8869/0276/files/Nicotinamide-Riboside-Veg-Capsules-120ct-Main-Image-V001.jpg?v=1762269187',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'bulksupplements',
    brands: { brand_name: 'BulkSupplements' },
    supplement_name: 'NR',
    shopify_product_gid: 'gid://shopify/Product/8085332295874',
    shopify_variant_gid: 'gid://shopify/ProductVariant/45141635006658',
    shopify_store_domain: 'bulksupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-spermidine',
    product_name: 'Nutricost Spermidine Wheat Germ',
    product_description:
      'Nutricost spermidine pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 49.97,
    product_url: 'https://nutricost.com/products/nutricost-spermidine-wheat-germ',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_SpermidineWheatGerm_500MGX3_120CAP_225CC_Front1_Square.jpg?v=1738267881',
    servings_per_container: 40,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Spermidine',
    shopify_product_gid: 'gid://shopify/Product/8049384227046',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43514733232358',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-pqq',
    product_name: 'Nutricost PQQ Capsules',
    product_description:
      'Nutricost pqq pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 14.97,
    product_url: 'https://nutricost.com/products/nutricost-pqq-20mg-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_PQQ_20MG_60CAP_Front1.jpg?v=1745435258',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'PQQ',
    shopify_product_gid: 'gid://shopify/Product/3702337634378',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28759523786826',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-glucosamine',
    product_name: 'Nutricost Glucosamine + Chondroitin + MSM Tablets',
    product_description:
      'Nutricost glucosamine pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 24.97,
    product_url: 'https://nutricost.com/products/nutricost-glucosamine-chondroitin-msm-tablets',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Glucosamine_1000MG_Chondroitin_45MG_MSM_210MG_240TAB_500CC_Front_Square.jpg?v=1779824876',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Glucosamine',
    shopify_product_gid: 'gid://shopify/Product/6892507988161',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40604354347201',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Tablets'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-bulksupplements-chondroitin',
    product_name: 'Chondroitin Sulfate Powder',
    product_description:
      'BulkSupplements chondroitin pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 21.97,
    product_url: 'https://bulksupplements.com/products/chondroitin-sulfate-powder',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0114/8869/0276/files/Chondroitin-Sulfate-Powder-100g-Main-Image-V002.jpg?v=1762198120',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'bulksupplements',
    brands: { brand_name: 'BulkSupplements' },
    supplement_name: 'Chondroitin',
    shopify_product_gid: 'gid://shopify/Product/3929079939183',
    shopify_variant_gid: 'gid://shopify/ProductVariant/32133387649135',
    shopify_store_domain: 'bulksupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-msm',
    product_name: 'Nutricost MSM Tablets',
    product_description:
      'Nutricost msm pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 19.97,
    product_url: 'https://nutricost.com/products/nutricost-msm-tablets',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_MSM_1000MGX2_240TAB_400CC_Front_Square_0af46b34-db0c-4471-9589-859fbe363c11.jpg?v=1777932299',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'MSM',
    shopify_product_gid: 'gid://shopify/Product/7723673911526',
    shopify_variant_gid: 'gid://shopify/ProductVariant/42761850650854',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Tablets'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-hyaluronic-acid',
    product_name: 'Nutricost Hyaluronic Acid Capsules',
    product_description:
      'Nutricost hyaluronic acid pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 15.97,
    product_url: 'https://nutricost.com/products/hyaluronic-acid',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_HyaluronicAcid_100MG_V1_120CAP_175CC_Front_Square.jpg?v=1782510931',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Hyaluronic Acid',
    shopify_product_gid: 'gid://shopify/Product/3814696648778',
    shopify_variant_gid: 'gid://shopify/ProductVariant/29380060577866',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-piping-rock-silica',
    product_name: 'Silica (Horsetail), 500 mg, 100 Quick Release Capsules',
    product_description:
      'Piping Rock silica pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 8.49,
    product_url: 'https://www.pipingrock.com/products/silica-horsetail-500-mg-100-quick-release-capsules-2141',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0640/7323/6718/files/silica-horsetail-500-mg-100-quick-release-capsules-2141.jpg?v=1782340696',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'piping-rock',
    brands: { brand_name: 'Piping Rock' },
    supplement_name: 'Silica',
    shopify_product_gid: 'gid://shopify/Product/7782034735342',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43261431808238',
    shopify_store_domain: 'www.pipingrock.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-keratin',
    product_name: 'Nutricost Keratin Capsules',
    product_description:
      'Nutricost keratin pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 16.97,
    product_url: 'https://nutricost.com/products/nutricost-keratin-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Keratin_500MG_120CAP_275CC_Front_Square.jpg?v=1773071570',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Keratin',
    shopify_product_gid: 'gid://shopify/Product/8951066362086',
    shopify_variant_gid: 'gid://shopify/ProductVariant/45729752350950',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-piping-rock-hemp-seed-oil',
    product_name: 'Hemp Seed Oil (Cold Pressed), 1400 mg (per serving), 180 Quick Release Softgels',
    product_description:
      'Piping Rock hemp seed oil pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 13.99,
    product_url: 'https://www.pipingrock.com/products/hemp-seed-oil-cold-pressed-1400-mg-per-serving-180-quick-release-softgels-614',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0640/7323/6718/files/hemp-seed-oil-cold-pressed-1400-mg-per-serving-180-quick-release-softgels-614.jpg?v=1782342380',
    servings_per_container: 180,
    servings_per_day: 1,
    brand_id: 'piping-rock',
    brands: { brand_name: 'Piping Rock' },
    supplement_name: 'Hemp Seed Oil',
    shopify_product_gid: 'gid://shopify/Product/7782088147182',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43261553017070',
    shopify_store_domain: 'www.pipingrock.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-mct-oil',
    product_name: 'Nutricost C8 MCT Oil Powder',
    product_description:
      'Nutricost mct oil pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 18.97,
    product_url: 'https://nutricost.com/products/nutricost-c8-mct-oil-unflavored-powder',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/products/nutricost-c8-mct-oil-powder-879483.jpg?v=1689400081',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'MCT Oil',
    shopify_product_gid: 'gid://shopify/Product/3695175204938',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28695912251466',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-bulksupplements-green-tea-extract',
    product_name: 'Green Tea Extract Capsules',
    product_description:
      'BulkSupplements green tea extract pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 20.97,
    product_url: 'https://bulksupplements.com/products/green-tea-pills',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0114/8869/0276/files/Green-Tea-Extract-Capsules-180ct-Main-Image-V001.jpg?v=1762198571',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'bulksupplements',
    brands: { brand_name: 'BulkSupplements' },
    supplement_name: 'Green Tea Extract',
    shopify_product_gid: 'gid://shopify/Product/7709843095746',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43479100588226',
    shopify_store_domain: 'bulksupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-quercetin',
    product_name: 'Nutricost Quercetin (1000mg)',
    product_description:
      'Nutricost quercetin pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 21.97,
    product_url: 'https://nutricost.com/products/nutricost-quercetin-1000mg',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Quercetin_500MGX2_120CAP_225CC_Front_Square_1b5893d5-4c9c-49c3-9ddd-3f9a03d9832e.jpg?v=1779828484',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Quercetin',
    shopify_product_gid: 'gid://shopify/Product/6979465183425',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40888792580289',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-elderberry',
    product_name: 'Nutricost Elderberry Capsules',
    product_description:
      'Nutricost elderberry pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 13.97,
    product_url: 'https://nutricost.com/products/nutricost-elderberry-575mg-120-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Elderberry_575MG_120CAP_275CC_Front_Square.jpg?v=1776970166',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Elderberry',
    shopify_product_gid: 'gid://shopify/Product/3702375252042',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28759902486602',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-echinacea',
    product_name: 'Nutricost Echinacea Capsules',
    product_description:
      'Nutricost echinacea pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 16.97,
    product_url: 'https://nutricost.com/products/nutricost-echinacea-400mg-240-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Echinacea_800MG_240CAP_Front_4de8d992-49c8-41b4-bfb6-b27528f8b3a8.jpg?v=1724175632',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Echinacea',
    shopify_product_gid: 'gid://shopify/Product/3702141157450',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28758344138826',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-reishi-mushroom',
    product_name: 'Nutricost Organic Reishi Mushroom Powder',
    product_description:
      'Nutricost reishi mushroom pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 19.97,
    product_url: 'https://nutricost.com/products/nutricost-organic-reishi-mushroom-8-oz-powder',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_OrganicReishiMushroomPowder_8OZ_Front.jpg?v=1724346455',
    servings_per_container: 227,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Reishi Mushroom',
    shopify_product_gid: 'gid://shopify/Product/3728872505418',
    shopify_variant_gid: 'gid://shopify/ProductVariant/28977667539018',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-cordyceps',
    product_name: 'Nutricost Made With Organic Cordyceps Capsules',
    product_description:
      'Nutricost cordyceps pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 16.97,
    product_url: 'https://nutricost.com/products/nutricost-organic-cordyceps-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Cordyceps_MWO__550MG__P0__90CAP_175CC_Front1_Square.jpg?v=1745513553',
    servings_per_container: 90,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Cordyceps',
    shopify_product_gid: 'gid://shopify/Product/4787648462922',
    shopify_variant_gid: 'gid://shopify/ProductVariant/32512624033866',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-chaga-mushroom',
    product_name: 'Nutricost Organic Chaga Mushroom Powder',
    product_description:
      'Nutricost chaga mushroom pick with a verified Shopify variant, so shoppers can move straight from the supplement page into merchant cart checkout.',
    product_price: 24.97,
    product_url: 'https://nutricost.com/products/nutricost-100-organic-chaga-mushroom-powder-8oz',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_OrganicChagaMushroomPowder_UF_8OZ_25OZ_Front_Square.jpg?v=1775841749',
    servings_per_container: 227,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Chaga Mushroom',
    shopify_product_gid: 'gid://shopify/Product/4143725215818',
    shopify_variant_gid: 'gid://shopify/ProductVariant/30268721823818',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Shopify UCP', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
];
