import type { CuratedProductSeed } from './supplement-catalog';

/**
 * Shopify-sourced product seeds covering every catalog supplement that does
 * not have a hand-curated merchant listing. Each entry carries a live Shopify
 * product + variant ID verified against the merchant storefront, so every
 * supplement page can offer a working cart-permalink checkout. The product
 * name includes the exact variant that lands in the merchant cart.
 *
 * Regenerate with: node src/scripts/sourceShopifyProducts.mjs
 * Validate with:   npm run verify:shopify-catalog
 */
export const sourcedProductSeeds: CuratedProductSeed[] = [
  {
    product_id: 'real-global-healing-vitamin-d3',
    product_name: 'Organic Vitamin D3 5000 IU, 2 fl oz',
    product_description:
      'Global Healing vitamin d3 pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 24.95,
    product_url: 'https://globalhealing.com/products/organic-vitamin-d3-5000-iu',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0539/5621/4984/files/3000w_2361cc6d-f5e8-4af7-8328-467b3a2c8cf1.png?v=1769442601',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'global-healing',
    brands: { brand_name: 'Global Healing' },
    supplement_name: 'Vitamin D3',
    shopify_product_gid: 'gid://shopify/Product/7031857316040',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44403788939464',
    shopify_store_domain: 'globalhealing.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-naturewise-vitamin-k2',
    product_name: 'Vegan Vitamin K2 Softgels, 90 Count',
    product_description:
      'NatureWise vitamin k2 pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 14.99,
    product_url: 'https://naturewise.com/products/vegan-vitamin-k2',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0966/9062/files/Vegan_Vitamin_K2_-_90CT_-_PDP_-_Front.jpg?v=1754514479',
    servings_per_container: 90,
    servings_per_day: 1,
    brand_id: 'naturewise',
    brands: { brand_name: 'NatureWise' },
    supplement_name: 'Vitamin K2',
    shopify_product_gid: 'gid://shopify/Product/7102699208769',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40883320193089',
    shopify_store_domain: 'naturewise.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-horbaach-vitamin-c',
    product_name: 'Vitamin C 1000mg',
    product_description:
      'Horbaach vitamin c pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 20.19,
    product_url: 'https://horbaach.com/products/vitamin-c-1000mg-250-capsules-cl1393',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0589/5336/7731/products/image-0_3c0650b2-14e7-4d84-9e9f-f923aeb2e33e.png?v=1776762147',
    servings_per_container: 250,
    servings_per_day: 1,
    brand_id: 'horbaach',
    brands: { brand_name: 'Horbaach' },
    supplement_name: 'Vitamin C',
    shopify_product_gid: 'gid://shopify/Product/6955093000371',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40776615592115',
    shopify_store_domain: 'horbaach.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-vitamin-b12',
    product_name: 'Nutricost Vitamin B12 Capsules, 2000 MCG / 240 Caps',
    product_description:
      'Nutricost vitamin b12 pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 16.97,
    product_url: 'https://nutricost.com/products/nutricost-vitamin-b12-2000mcg-240-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Vitamin_B12_2000MCG_240CAP_Front_Square.jpg?v=1768597251',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Vitamin B12',
    shopify_product_gid: 'gid://shopify/Product/3702314270794',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44035440902374',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-double-wood-b-complex',
    product_name: 'Vitamin B Complex Drops, One Bottle',
    product_description:
      'Double Wood Supplements b-complex pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 19.95,
    product_url: 'https://doublewoodsupplements.com/products/vitamin-b-complex-drops',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0756/3867/files/VitaminB12Complex_Image_Front_a643bcfa-44e5-4d67-ac10-01d900f511e6.png?v=1767119238',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'double-wood',
    brands: { brand_name: 'Double Wood Supplements' },
    supplement_name: 'B-Complex',
    shopify_product_gid: 'gid://shopify/Product/7945773056194',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44544726237378',
    shopify_store_domain: 'doublewoodsupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Liquid'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-solaray-folate',
    product_name: 'Methyl Folate 1000mcg, 60ct / Lemon',
    product_description:
      'Solaray folate pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 17.09,
    product_url: 'https://solaray.com/products/methyl-folate',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0270/2317/9836/products/076280578959_4.jpg?v=1662571762',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'solaray',
    brands: { brand_name: 'Solaray' },
    supplement_name: 'Folate',
    shopify_product_gid: 'gid://shopify/Product/6796809011260',
    shopify_variant_gid: 'gid://shopify/ProductVariant/39844855349308',
    shopify_store_domain: 'solaray.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-carlson-labs-biotin',
    product_name: 'Biotin 5,000 mcg, 50 Capsules',
    product_description:
      'Carlson Labs biotin pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 7.9,
    product_url: 'https://carlsonlabs.com/products/biotin-5-000-mcg',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0687/2724/2969/files/088395249105_1__62819_8d0237ea-4377-460c-a2b6-1fb8433080fe.jpg?v=1748424229',
    servings_per_container: 50,
    servings_per_day: 1,
    brand_id: 'carlson-labs',
    brands: { brand_name: 'Carlson Labs' },
    supplement_name: 'Biotin',
    shopify_product_gid: 'gid://shopify/Product/8615864434905',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44952981700825',
    shopify_store_domain: 'carlsonlabs.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-jarrow-formulas-magnesium-glycinate',
    product_name: 'Magnesium Glycinate',
    product_description:
      'Jarrow Formulas magnesium glycinate pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 24.99,
    product_url: 'https://jarrow.com/products/magnesium-glycinate',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/2600/1286/files/MAGGLY990_082124_Front.png?v=1726601303',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'jarrow-formulas',
    brands: { brand_name: 'Jarrow Formulas' },
    supplement_name: 'Magnesium Glycinate',
    shopify_product_gid: 'gid://shopify/Product/7272876179499',
    shopify_variant_gid: 'gid://shopify/ProductVariant/41180936831019',
    shopify_store_domain: 'jarrow.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-purebulk-magnesium-citrate',
    product_name: 'Magnesium Citrate, Bags / 500 grams',
    product_description:
      'PureBulk magnesium citrate pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 14.95,
    product_url: 'https://purebulk.com/products/magnesium-citrate',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0012/6379/6273/files/magnesium-citrate.avif?v=1782825666',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'purebulk',
    brands: { brand_name: 'PureBulk' },
    supplement_name: 'Magnesium Citrate',
    shopify_product_gid: 'gid://shopify/Product/1789636050993',
    shopify_variant_gid: 'gid://shopify/ProductVariant/14286725382193',
    shopify_store_domain: 'purebulk.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-bulksupplements-zinc',
    product_name: 'Zinc Picolinate Softgels, Softgel / 240 Softgels',
    product_description:
      'BulkSupplements zinc pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 18.97,
    product_url: 'https://bulksupplements.com/products/zinc-picolinate',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0114/8869/0276/files/ZincPic_AMZ_f8e42040-c8da-4cb8-bc8c-e78ea5809fbb.jpg?v=1766439252',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'bulksupplements',
    brands: { brand_name: 'BulkSupplements' },
    supplement_name: 'Zinc',
    shopify_product_gid: 'gid://shopify/Product/7236513595586',
    shopify_variant_gid: 'gid://shopify/ProductVariant/42660919148738',
    shopify_store_domain: 'bulksupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-bronson-iron',
    product_name: 'Iron Bisglycinate - 25 mg, 180 Count',
    product_description:
      'Bronson iron pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 14.99,
    product_url: 'https://bronsonvitamins.com/products/iron-bisglycinate-25mg-180-vegetarian-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0653/4489/7258/files/1162-180IronBisglycinateBottle_Pills_682f912b-c00c-464a-a89a-715aa05c4c42.jpg?v=1730906985',
    servings_per_container: 180,
    servings_per_day: 1,
    brand_id: 'bronson',
    brands: { brand_name: 'Bronson' },
    supplement_name: 'Iron',
    shopify_product_gid: 'gid://shopify/Product/8051301482730',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44729623445738',
    shopify_store_domain: 'bronsonvitamins.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-carlson-labs-calcium',
    product_name: 'Chewable Calcium Citrate',
    product_description:
      'Carlson Labs calcium pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 36.9,
    product_url: 'https://carlsonlabs.com/products/chewable-calcium-citrate',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0687/2724/2969/files/088395050817_1__69458_1474f983-f442-4e26-b2fe-ce05e9981551.jpg?v=1748424349',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'carlson-labs',
    brands: { brand_name: 'Carlson Labs' },
    supplement_name: 'Calcium',
    shopify_product_gid: 'gid://shopify/Product/8615888322777',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44953024757977',
    shopify_store_domain: 'carlsonlabs.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-piping-rock-selenium',
    product_name: 'Selenium, 200 mcg, 250 Tablets',
    product_description:
      'Piping Rock selenium pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 7.49,
    product_url: 'https://www.pipingrock.com/products/selenium-200-mcg-250-tablets-1853',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0640/7323/6718/files/selenium-200-mcg-250-tablets-1853.jpg?v=1782338119',
    servings_per_container: 250,
    servings_per_day: 1,
    brand_id: 'piping-rock',
    brands: { brand_name: 'Piping Rock' },
    supplement_name: 'Selenium',
    shopify_product_gid: 'gid://shopify/Product/7782047285486',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43261454745838',
    shopify_store_domain: 'www.pipingrock.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Tablets'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-maryruth-organics-iodine',
    product_name: 'Iodine Liquid Drops',
    product_description:
      'MaryRuth Organics iodine pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 21.95,
    product_url: 'https://maryruthorganics.com/products/iodine-liquid-drops',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0883/6750/files/ORG_Iodine_Drops_1oz_Unlfavored_2d33b484-91ae-4cbb-ae34-bab53e004cc4.png?v=1772978822',
    servings_per_container: 450,
    servings_per_day: 1,
    brand_id: 'maryruth-organics',
    brands: { brand_name: 'MaryRuth Organics' },
    supplement_name: 'Iodine',
    shopify_product_gid: 'gid://shopify/Product/3877406244961',
    shopify_variant_gid: 'gid://shopify/ProductVariant/29226771120225',
    shopify_store_domain: 'maryruthorganics.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Liquid'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nature-made-omega-3-fish-oil',
    product_name: 'Fish Oil 1200 mg Softgels, 100',
    product_description:
      'Nature Made omega-3 fish oil pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 17.49,
    product_url: 'https://naturemade.com/products/nature-made-fish-oil-1-200-mg-softgels',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0066/7569/3639/files/NM1328PK000745FISHOIL_5A009400ccfront.png?v=1695678265',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'nature-made',
    brands: { brand_name: 'Nature Made' },
    supplement_name: 'Omega-3 Fish Oil',
    shopify_product_gid: 'gid://shopify/Product/1818350125127',
    shopify_variant_gid: 'gid://shopify/ProductVariant/17622126657607',
    shopify_store_domain: 'naturemade.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-micro-ingredients-krill-oil',
    product_name: 'Micro Ingredients Antarctic Krill Oil 2000mg, 240 softgels, 240 Softgels',
    product_description:
      'Micro Ingredients krill oil pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 34.95,
    product_url: 'https://microingredients.com/products/antarctic-krill-oil-supplement',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/1866/1287/files/Product-Shopify_c968ea5b-c747-4ae0-92b5-6da227274c96.png?v=1782172332',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'micro-ingredients',
    brands: { brand_name: 'Micro Ingredients' },
    supplement_name: 'Krill Oil',
    shopify_product_gid: 'gid://shopify/Product/8137641328867',
    shopify_variant_gid: 'gid://shopify/ProductVariant/47409804017891',
    shopify_store_domain: 'microingredients.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nature-made-algal-oil',
    product_name: 'Algae Omega-3 540 mg Softgels, 70',
    product_description:
      'Nature Made algal oil pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 29.99,
    product_url: 'https://naturemade.com/products/algae-omega-3-softgels',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0066/7569/3639/files/NM3296PK001546ALGAEOMEGA-3_5A007225ccfront.png?v=1717684838',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'nature-made',
    brands: { brand_name: 'Nature Made' },
    supplement_name: 'Algal Oil',
    shopify_product_gid: 'gid://shopify/Product/7454644568203',
    shopify_variant_gid: 'gid://shopify/ProductVariant/42483151569035',
    shopify_store_domain: 'naturemade.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-cod-liver-oil',
    product_name: 'Nutricost Cod Liver Oil',
    product_description:
      'Nutricost cod liver oil pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 17.97,
    product_url: 'https://nutricost.com/products/nutricost-cod-liver-oil',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_CodLiverOil_120SFG_1000MG_Front.jpg?v=1695320532',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Cod Liver Oil',
    shopify_product_gid: 'gid://shopify/Product/8177596367078',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43718962938086',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Liquid'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-zhou-nutrition-collagen-peptides',
    product_name: 'Collagen Peptides',
    product_description:
      'Zhou Nutrition collagen peptides pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 30.59,
    product_url: 'https://zhounutrition.com/products/collagen-peptides',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0746/6555/files/CollagenPeptides_bf32a902-8425-457a-bc90-8458e173ecee.png?v=1777555189',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'zhou-nutrition',
    brands: { brand_name: 'Zhou Nutrition' },
    supplement_name: 'Collagen Peptides',
    shopify_product_gid: 'gid://shopify/Product/423708098598',
    shopify_variant_gid: 'gid://shopify/ProductVariant/30721317830787',
    shopify_store_domain: 'zhounutrition.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-bulksupplements-beetroot',
    product_name: 'Organic Beet Root Powder, Powder / 500 Grams (1.1 lbs)',
    product_description:
      'BulkSupplements beetroot pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 22.97,
    product_url: 'https://bulksupplements.com/products/beet-root-powder',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0114/8869/0276/files/Organic-Beet-Root-Powder-500g-Main-Image-V002_ff3a60a7-384f-4062-8384-dea8a717ffdb.jpg?v=1762198154',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'bulksupplements',
    brands: { brand_name: 'BulkSupplements' },
    supplement_name: 'Beetroot',
    shopify_product_gid: 'gid://shopify/Product/3929082167407',
    shopify_variant_gid: 'gid://shopify/ProductVariant/32133376245871',
    shopify_store_domain: 'bulksupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-toniiq-ashwagandha',
    product_name: 'Ashwagandha 10%',
    product_description:
      'Toniiq ashwagandha pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 24.97,
    product_url: 'https://toniiq.com/products/ashwagandha',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0257/8723/products/Ashwagandha_Mockup_front_8oz.png?v=1676931335',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'toniiq',
    brands: { brand_name: 'Toniiq' },
    supplement_name: 'Ashwagandha',
    shopify_product_gid: 'gid://shopify/Product/3748566925389',
    shopify_variant_gid: 'gid://shopify/ProductVariant/29181222191181',
    shopify_store_domain: 'toniiq.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-double-wood-rhodiola-rosea',
    product_name: 'Rhodiola Rosea Extract Supplement, One Bottle',
    product_description:
      'Double Wood Supplements rhodiola rosea pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 17.95,
    product_url: 'https://doublewoodsupplements.com/products/rhodiola-rosea-extract',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0756/3867/files/Rhodiola_Front_Bottle.jpg?v=1781621269',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'double-wood',
    brands: { brand_name: 'Double Wood Supplements' },
    supplement_name: 'Rhodiola Rosea',
    shopify_product_gid: 'gid://shopify/Product/1316231348313',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44435956367554',
    shopify_store_domain: 'doublewoodsupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-micro-ingredients-panax-ginseng',
    product_name: 'Micro Ingredients Panax Ginseng, 300 Softgels',
    product_description:
      'Micro Ingredients panax ginseng pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 25.95,
    product_url: 'https://microingredients.com/products/ginseng-supplement-red-panax-extractum-softgels',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/1866/1287/files/Product-Shopify1.jpg?v=1774388187',
    servings_per_container: 300,
    servings_per_day: 1,
    brand_id: 'micro-ingredients',
    brands: { brand_name: 'Micro Ingredients' },
    supplement_name: 'Panax Ginseng',
    shopify_product_gid: 'gid://shopify/Product/1524504789028',
    shopify_variant_gid: 'gid://shopify/ProductVariant/11954131796004',
    shopify_store_domain: 'microingredients.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-solaray-maca-root',
    product_name: 'Maca Root Extract 300 mg, 60ct',
    product_description:
      'Solaray maca root pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 22.29,
    product_url: 'https://solaray.com/products/maca-root-extract',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0270/2317/9836/files/076280036879_4.png?v=1776093228',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'solaray',
    brands: { brand_name: 'Solaray' },
    supplement_name: 'Maca Root',
    shopify_product_gid: 'gid://shopify/Product/6796814876732',
    shopify_variant_gid: 'gid://shopify/ProductVariant/39844863672380',
    shopify_store_domain: 'solaray.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-toniiq-turmeric-curcumin',
    product_name: 'Turmeric Curcumin 97%',
    product_description:
      'Toniiq turmeric curcumin pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 27.74,
    product_url: 'https://toniiq.com/products/turmeric-curcumin',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0257/8723/files/Website_Image_Curcumin_Pura_97_120_Capsules_US.jpg?v=1758650546',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'toniiq',
    brands: { brand_name: 'Toniiq' },
    supplement_name: 'Turmeric Curcumin',
    shopify_product_gid: 'gid://shopify/Product/7883473879254',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43687704658134',
    shopify_store_domain: 'toniiq.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-horbaach-ginger',
    product_name: 'Ginger Root Extract',
    product_description:
      'Horbaach ginger pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 10.99,
    product_url: 'https://horbaach.com/products/ginger-root-extract-150-capsules-cl3293',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0589/5336/7731/files/image-0_5c1123a5-2096-4079-8037-b8253282d115.png?v=1780084776',
    servings_per_container: 150,
    servings_per_day: 1,
    brand_id: 'horbaach',
    brands: { brand_name: 'Horbaach' },
    supplement_name: 'Ginger',
    shopify_product_gid: 'gid://shopify/Product/6955091984563',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40776614215859',
    shopify_store_domain: 'horbaach.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-piping-rock-garlic-extract',
    product_name: 'Garlinase 5000 Garlic Extract, 100 Enteric Coated Tablets',
    product_description:
      'Piping Rock garlic extract pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 30.89,
    product_url: 'https://www.pipingrock.com/products/garlinase-5000-garlic-extract-100-enteric-coated-tablets-41583',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0640/7323/6718/files/garlinase-5000-garlic-extract-100-enteric-coated-tablets-41583.jpg?v=1782346294',
    servings_per_container: 100,
    servings_per_day: 1,
    brand_id: 'piping-rock',
    brands: { brand_name: 'Piping Rock' },
    supplement_name: 'Garlic Extract',
    shopify_product_gid: 'gid://shopify/Product/7782089031918',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43261554426094',
    shopify_store_domain: 'www.pipingrock.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Tablets'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-jarrow-formulas-milk-thistle',
    product_name: 'Milk Thistle (2-Pack), 100ct',
    product_description:
      'Jarrow Formulas milk thistle pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 35.98,
    product_url: 'https://jarrow.com/products/milk-thistle-silymarin-150-mg-veggie-caps',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/2600/1286/files/SILY_00705f19-ee77-454c-95c6-42873778c01b.png?v=1779474886',
    servings_per_container: 100,
    servings_per_day: 1,
    brand_id: 'jarrow-formulas',
    brands: { brand_name: 'Jarrow Formulas' },
    supplement_name: 'Milk Thistle',
    shopify_product_gid: 'gid://shopify/Product/1793386676267',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40213523529771',
    shopify_store_domain: 'jarrow.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-global-healing-holy-basil',
    product_name: 'Tulsi/Holy Basil, 2 fl oz',
    product_description:
      'Global Healing holy basil pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 24.95,
    product_url: 'https://globalhealing.com/products/tulsi-holy-basil',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0539/5621/4984/products/3000w_2ee9e368-80f6-48b4-be59-40b411029a13.png?v=1762459280',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'global-healing',
    brands: { brand_name: 'Global Healing' },
    supplement_name: 'Holy Basil',
    shopify_product_gid: 'gid://shopify/Product/6734043709640',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44403760267464',
    shopify_store_domain: 'globalhealing.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-bacopa-monnieri',
    product_name: 'Nutricost Bacopa Monnieri',
    product_description:
      'Nutricost bacopa monnieri pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 18.97,
    product_url: 'https://nutricost.com/products/nutricost-bacopa-monnieri',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_BacopaMonnieri_500MG_120CAP_275CC_Front_Square.jpg?v=1775680375',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Bacopa Monnieri',
    shopify_product_gid: 'gid://shopify/Product/6881372995777',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40562214633665',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-bronson-ginkgo-biloba',
    product_name: 'Ginkgo Biloba, 120 Count',
    product_description:
      'Bronson ginkgo biloba pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 9.99,
    product_url: 'https://bronsonvitamins.com/products/gingko-biloba-500-mg-120-vegetarian-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0653/4489/7258/files/1163-120GinkgoBilobaBottle_Pills_f80ff135-a429-4584-bb80-aea8a7cb846a.jpg?v=1776780355',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'bronson',
    brands: { brand_name: 'Bronson' },
    supplement_name: 'Ginkgo Biloba',
    shopify_product_gid: 'gid://shopify/Product/8051301515498',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44029553377514',
    shopify_store_domain: 'bronsonvitamins.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-micro-ingredients-lion-s-mane-mushroom',
    product_name: 'Micro Ingredients Organic Lions Mane Mushroom Supplement Powder, 16 oz',
    product_description:
      'Micro Ingredients lion\'s mane mushroom pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 38.95,
    product_url: 'https://microingredients.com/products/organic-lions-mane-mushroom-powder',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/1866/1287/files/Lionsmaneweb1.jpg?v=1770931129',
    servings_per_container: 302,
    servings_per_day: 1,
    brand_id: 'micro-ingredients',
    brands: { brand_name: 'Micro Ingredients' },
    supplement_name: 'Lion\'s Mane Mushroom',
    shopify_product_gid: 'gid://shopify/Product/4603381743749',
    shopify_variant_gid: 'gid://shopify/ProductVariant/45887957467363',
    shopify_store_domain: 'microingredients.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-purebulk-alpha-gpc',
    product_name: 'Alpha GPC, Bags / 10 grams',
    product_description:
      'PureBulk alpha-gpc pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 6.5,
    product_url: 'https://purebulk.com/products/alpha-gpc-pure',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0012/6379/6273/products/alpha-gpc-bag_1_44447c25-bd00-426e-a2ae-6f0465bc8b5d.jpg?v=1666796759',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'purebulk',
    brands: { brand_name: 'PureBulk' },
    supplement_name: 'Alpha-GPC',
    shopify_product_gid: 'gid://shopify/Product/1803399462961',
    shopify_variant_gid: 'gid://shopify/ProductVariant/14339600220209',
    shopify_store_domain: 'purebulk.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-cdp-choline',
    product_name: 'Nutricost Cognizin Citicoline',
    product_description:
      'Nutricost cdp-choline pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 38.97,
    product_url: 'https://nutricost.com/products/nutricost-cognizin-citicoline',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Cognizin_500MGX2_60CAP_175CC_Front_Square.jpg?v=1778882817',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'CDP-Choline',
    shopify_product_gid: 'gid://shopify/Product/9723063828710',
    shopify_variant_gid: 'gid://shopify/ProductVariant/47671264051430',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nusapure-phosphatidylserine',
    product_name: 'NusaPure Phosphatidylserine Memory Ultimate Complex 1000mg 200 Vegetarian Caps (Vegan, Non-GMO)',
    product_description:
      'NusaPure phosphatidylserine pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 25.95,
    product_url: 'https://nusapure.com/products/nusapure-phosphatidylserine-memory-ultimate-complex-1000mg-200-vegetarian-caps-vegan-non-gmo',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0978/6785/8240/files/f9aa69b7.jpg?v=1773759230',
    servings_per_container: 200,
    servings_per_day: 1,
    brand_id: 'nusapure',
    brands: { brand_name: 'NusaPure' },
    supplement_name: 'Phosphatidylserine',
    shopify_product_gid: 'gid://shopify/Product/10073777439040',
    shopify_variant_gid: 'gid://shopify/ProductVariant/51628474237248',
    shopify_store_domain: 'nusapure.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-naturewise-l-theanine',
    product_name: 'L-Theanine, 200 mg / 120 Count',
    product_description:
      'NatureWise l-theanine pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 11.99,
    product_url: 'https://naturewise.com/products/l-theanine',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0966/9062/files/NW_-_L-Theanine_-_1_-_Main_Image.jpg?v=1773170409',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'naturewise',
    brands: { brand_name: 'NatureWise' },
    supplement_name: 'L-Theanine',
    shopify_product_gid: 'gid://shopify/Product/14969010291060',
    shopify_variant_gid: 'gid://shopify/ProductVariant/54056429912436',
    shopify_store_domain: 'naturewise.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-codeage-glycine',
    product_name: 'Liposomal Glycine',
    product_description:
      'Codeage glycine pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 39.99,
    product_url: 'https://codeage.com/products/liposomal-glycine-free-form-amino-acid-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0014/4719/8797/files/LiposomalGlycine_front.jpg?v=1775228867',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'codeage',
    brands: { brand_name: 'Codeage' },
    supplement_name: 'Glycine',
    shopify_product_gid: 'gid://shopify/Product/14893912719729',
    shopify_variant_gid: 'gid://shopify/ProductVariant/52032930677105',
    shopify_store_domain: 'codeage.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-double-wood-l-tyrosine',
    product_name: 'L-Tyrosine Supplement, One Bottle',
    product_description:
      'Double Wood Supplements l-tyrosine pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 19.95,
    product_url: 'https://doublewoodsupplements.com/products/l-tyrosine',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0756/3867/files/LTyrosine_Front_Image_bija7y_aa248c16-3ab9-46b8-82fc-b459e09db9db.png?v=1767120851',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'double-wood',
    brands: { brand_name: 'Double Wood Supplements' },
    supplement_name: 'L-Tyrosine',
    shopify_product_gid: 'gid://shopify/Product/7792960831682',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44435976552642',
    shopify_store_domain: 'doublewoodsupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-maryruth-organics-nac',
    product_name: 'N-acetyl-cysteine (NAC)',
    product_description:
      'MaryRuth Organics nac pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 19.95,
    product_url: 'https://maryruthorganics.com/products/nac-supplement-n-acetyl-cysteine',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0883/6750/files/NAC_Capsules_120ct.png?v=1772987302',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'maryruth-organics',
    brands: { brand_name: 'MaryRuth Organics' },
    supplement_name: 'NAC',
    shopify_product_gid: 'gid://shopify/Product/6902376005729',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40574482808929',
    shopify_store_domain: 'maryruthorganics.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-carlson-labs-l-carnitine',
    product_name: 'Acetyl L-Carnitine, 60 Capsules',
    product_description:
      'Carlson Labs l-carnitine pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 23.9,
    product_url: 'https://carlsonlabs.com/products/acetyl-l-carnitine',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0687/2724/2969/files/088395079207_1.jpg?v=1754344344',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'carlson-labs',
    brands: { brand_name: 'Carlson Labs' },
    supplement_name: 'L-Carnitine',
    shopify_product_gid: 'gid://shopify/Product/8615918043353',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44953096093913',
    shopify_store_domain: 'carlsonlabs.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-solaray-gaba',
    product_name: 'Plant-Sourced GABA, 30 ct',
    product_description:
      'Solaray gaba pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 19.49,
    product_url: 'https://solaray.com/products/plant-sourced-gaba',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0270/2317/9836/files/076280346688-Solaray-GABA30ct_4_Final.png?v=1741619569',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'solaray',
    brands: { brand_name: 'Solaray' },
    supplement_name: 'GABA',
    shopify_product_gid: 'gid://shopify/Product/7952071753788',
    shopify_variant_gid: 'gid://shopify/ProductVariant/42693591302204',
    shopify_store_domain: 'solaray.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-melatonin',
    product_name: 'Nutricost Melatonin Tablets, 3MG',
    product_description:
      'Nutricost melatonin pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 11.97,
    product_url: 'https://nutricost.com/products/nutricost-melatonin-3mg-240-caps',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_Melatonin_3MG_240TBL_150CCCOMPAX_Front_Square.jpg?v=1775839709',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Melatonin',
    shopify_product_gid: 'gid://shopify/Product/6722586247361',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40129845002433',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Tablets'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-codeage-apigenin',
    product_name: 'Liposomal Apigenin',
    product_description:
      'Codeage apigenin pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 29.99,
    product_url: 'https://codeage.com/products/liposomal-apigenin-50mg-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0014/4719/8797/files/LiposomalApigenin_front_NSF.jpg?v=1762199068',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'codeage',
    brands: { brand_name: 'Codeage' },
    supplement_name: 'Apigenin',
    shopify_product_gid: 'gid://shopify/Product/6731828166761',
    shopify_variant_gid: 'gid://shopify/ProductVariant/39687040041065',
    shopify_store_domain: 'codeage.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-horbaach-valerian-root',
    product_name: 'Valerian Root',
    product_description:
      'Horbaach valerian root pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 9.89,
    product_url: 'https://horbaach.com/products/valerian-root-2oz-liquid-cl39552',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0589/5336/7731/files/image-0_ed76eeee-0a2c-49da-b9a0-0fbc446ef232.png?v=1776762826',
    servings_per_container: 32,
    servings_per_day: 1,
    brand_id: 'horbaach',
    brands: { brand_name: 'Horbaach' },
    supplement_name: 'Valerian Root',
    shopify_product_gid: 'gid://shopify/Product/6955102699699',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40776628207795',
    shopify_store_domain: 'horbaach.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Liquid'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-purebulk-passionflower',
    product_name: 'Passion Flower Extract, Bags / 100 grams',
    product_description:
      'PureBulk passionflower pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 9.25,
    product_url: 'https://purebulk.com/products/passion-flower-extract',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0012/6379/6273/files/PassionFlowerExtract-bagonly.jpg?v=1761321224',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'purebulk',
    brands: { brand_name: 'PureBulk' },
    supplement_name: 'Passionflower',
    shopify_product_gid: 'gid://shopify/Product/8196748476613',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44394476536005',
    shopify_store_domain: 'purebulk.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-maryruth-organics-lemon-balm',
    product_name: 'Organic Lemon Balm Leaf Liquid Drops',
    product_description:
      'MaryRuth Organics lemon balm pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 19.95,
    product_url: 'https://maryruthorganics.com/products/lemon-balm-leaf-1-oz-melissa-officinalis',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0883/6750/files/ORG_Lemon_Balm_Drops_1oz_Unflavored.png?v=1773049484',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'maryruth-organics',
    brands: { brand_name: 'MaryRuth Organics' },
    supplement_name: 'Lemon Balm',
    shopify_product_gid: 'gid://shopify/Product/4598273736801',
    shopify_variant_gid: 'gid://shopify/ProductVariant/32145737089121',
    shopify_store_domain: 'maryruthorganics.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Liquid'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nutricost-probiotics',
    product_name: 'Nutricost Probiotic Complex Capsules, 50 Billion CFU',
    product_description:
      'Nutricost probiotics pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 21.97,
    product_url: 'https://nutricost.com/products/nutricost-probiotic-complex-50-billion-cfu-60-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0222/4128/0074/files/NTC_ProbioticComplex_50Billion_60CAP_150CCCOMPAX_Front_Square.jpg?v=1781286841',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'nutricost',
    brands: { brand_name: 'Nutricost' },
    supplement_name: 'Probiotics',
    shopify_product_gid: 'gid://shopify/Product/3703027204170',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43517437968614',
    shopify_store_domain: 'nutricost.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-bulksupplements-prebiotic-fiber',
    product_name: 'Organic Inulin Powder, Powder / 500 Grams (1.1 lbs)',
    product_description:
      'BulkSupplements prebiotic fiber pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 25.97,
    product_url: 'https://bulksupplements.com/products/inulin-fos-powder',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0114/8869/0276/files/Organic-Inulin-Powder-500g-Main-Image-V004_cd754a4d-da9c-4c5c-b452-188ca04e439e.jpg?v=1780513097',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'bulksupplements',
    brands: { brand_name: 'BulkSupplements' },
    supplement_name: 'Prebiotic Fiber',
    shopify_product_gid: 'gid://shopify/Product/3929074630767',
    shopify_variant_gid: 'gid://shopify/ProductVariant/32133415567471',
    shopify_store_domain: 'bulksupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-solaray-psyllium-husk',
    product_name: 'Psyllium Husk 525mg, 100ct',
    product_description:
      'Solaray psyllium husk pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 10.19,
    product_url: 'https://solaray.com/products/psyllium-husk',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0270/2317/9836/files/076280014600-Solaray-PsylliumHusk100ct-1371854-0825_Final_4.png?v=1767638947',
    servings_per_container: 100,
    servings_per_day: 1,
    brand_id: 'solaray',
    brands: { brand_name: 'Solaray' },
    supplement_name: 'Psyllium Husk',
    shopify_product_gid: 'gid://shopify/Product/6796822446140',
    shopify_variant_gid: 'gid://shopify/ProductVariant/39844873306172',
    shopify_store_domain: 'solaray.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-codeage-digestive-enzymes',
    product_name: 'Fermented Digestive Enzymes Large',
    product_description:
      'Codeage digestive enzymes pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 29.99,
    product_url: 'https://codeage.com/products/fermented-enzymes',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0014/4719/8797/files/FermentedDigestiveEnzymes_front.jpg?v=1761592974',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'codeage',
    brands: { brand_name: 'Codeage' },
    supplement_name: 'Digestive Enzymes',
    shopify_product_gid: 'gid://shopify/Product/4179253264461',
    shopify_variant_gid: 'gid://shopify/ProductVariant/30376392294477',
    shopify_store_domain: 'codeage.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-zhou-nutrition-apple-cider-vinegar',
    product_name: 'Apple Cider Vinegar Gummies',
    product_description:
      'Zhou Nutrition apple cider vinegar pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 14.69,
    product_url: 'https://zhounutrition.com/products/apple-cider-vinegar-gummies',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0746/6555/files/AppleCiderVinegar-1_6673014c-0fbb-4b60-8390-9becd69a748d.png?v=1777552521',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'zhou-nutrition',
    brands: { brand_name: 'Zhou Nutrition' },
    supplement_name: 'Apple Cider Vinegar',
    shopify_product_gid: 'gid://shopify/Product/4868921720963',
    shopify_variant_gid: 'gid://shopify/ProductVariant/33300271923331',
    shopify_store_domain: 'zhounutrition.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Gummies'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-naturewise-berberine',
    product_name: 'Berberine, 60 Count',
    product_description:
      'NatureWise berberine pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 34.99,
    product_url: 'https://naturewise.com/products/berberine',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0966/9062/files/NW_-_Berberine_Complex_-_1_-_Main_Image_2_1.jpg?v=1768436061',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'naturewise',
    brands: { brand_name: 'NatureWise' },
    supplement_name: 'Berberine',
    shopify_product_gid: 'gid://shopify/Product/14788115071348',
    shopify_variant_gid: 'gid://shopify/ProductVariant/53070935753076',
    shopify_store_domain: 'naturewise.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nusapure-chromium',
    product_name: 'NusaPure Chromium Picolinate 1000mcg 240 Veggie Capsules (Non-GMO, Vegan)',
    product_description:
      'NusaPure chromium pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 21.29,
    product_url: 'https://nusapure.com/products/nusapure-chromium-picolinate-1000mcg-240-veggie-capsules-non-gmo-vegan',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0978/6785/8240/files/6049c0d1.jpg?v=1773759218',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'nusapure',
    brands: { brand_name: 'NusaPure' },
    supplement_name: 'Chromium',
    shopify_product_gid: 'gid://shopify/Product/10073776357696',
    shopify_variant_gid: 'gid://shopify/ProductVariant/51628473123136',
    shopify_store_domain: 'nusapure.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-piping-rock-cinnamon-extract',
    product_name: 'Ceylon Cinnamon Extract, 2000 mg, 180 Capsules',
    product_description:
      'Piping Rock cinnamon extract pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 18.99,
    product_url: 'https://www.pipingrock.com/products/ceylon-cinnamon-extract-2000-mg-180-capsules-22751',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0640/7323/6718/files/ceylon-cinnamon-extract-2000-mg-180-capsules-22751.jpg?v=1782340342',
    servings_per_container: 180,
    servings_per_day: 1,
    brand_id: 'piping-rock',
    brands: { brand_name: 'Piping Rock' },
    supplement_name: 'Cinnamon Extract',
    shopify_product_gid: 'gid://shopify/Product/7781996495086',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43261372858606',
    shopify_store_domain: 'www.pipingrock.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-solaray-myo-inositol',
    product_name: 'Inositol Powder 700mg, 2oz',
    product_description:
      'Solaray myo-inositol pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 16.09,
    product_url: 'https://solaray.com/products/inositol',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0270/2317/9836/products/076280043556_4n.png?v=1646081903',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'solaray',
    brands: { brand_name: 'Solaray' },
    supplement_name: 'Myo-Inositol',
    shopify_product_gid: 'gid://shopify/Product/4622155055164',
    shopify_variant_gid: 'gid://shopify/ProductVariant/32438875127868',
    shopify_store_domain: 'solaray.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Bulk powder'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nature-made-coq10',
    product_name: 'CoQ10 100 mg Softgels, 40',
    product_description:
      'Nature Made coq10 pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 26.39,
    product_url: 'https://naturemade.com/products/nature-made-coq10-100-mg-softgels',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0066/7569/3639/files/NM1894PK001109CoQ10_5A044150ccfront.png?v=1684878243',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'nature-made',
    brands: { brand_name: 'Nature Made' },
    supplement_name: 'CoQ10',
    shopify_product_gid: 'gid://shopify/Product/1840382279751',
    shopify_variant_gid: 'gid://shopify/ProductVariant/41069557776523',
    shopify_store_domain: 'naturemade.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-double-wood-nattokinase',
    product_name: 'Nattokinase Supplement, One Bottle',
    product_description:
      'Double Wood Supplements nattokinase pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 19.95,
    product_url: 'https://doublewoodsupplements.com/products/nattokinase',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0756/3867/files/Nattokinase_Front_Image_uv8nho_ab43b261-be8a-40de-90a3-e7b078195b22.jpg?v=1767121260',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'double-wood',
    brands: { brand_name: 'Double Wood Supplements' },
    supplement_name: 'Nattokinase',
    shopify_product_gid: 'gid://shopify/Product/7463747813570',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44435933593794',
    shopify_store_domain: 'doublewoodsupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-zhou-nutrition-resveratrol',
    product_name: 'Resveratrol',
    product_description:
      'Zhou Nutrition resveratrol pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 25.69,
    product_url: 'https://zhounutrition.com/products/resveratrol',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0746/6555/files/Resveratrol-1_1.png?v=1777572472',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'zhou-nutrition',
    brands: { brand_name: 'Zhou Nutrition' },
    supplement_name: 'Resveratrol',
    shopify_product_gid: 'gid://shopify/Product/1696668740',
    shopify_variant_gid: 'gid://shopify/ProductVariant/5959379681318',
    shopify_store_domain: 'zhounutrition.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-jarrow-formulas-nmn',
    product_name: 'NMN (Nicotinamide Mononucleotide)',
    product_description:
      'Jarrow Formulas nmn pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 62.99,
    product_url: 'https://jarrow.com/products/nmn-125-mg-60-tablets',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/2600/1286/files/NMN-012523-Front.png?v=1682469008',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'jarrow-formulas',
    brands: { brand_name: 'Jarrow Formulas' },
    supplement_name: 'NMN',
    shopify_product_gid: 'gid://shopify/Product/4876355928107',
    shopify_variant_gid: 'gid://shopify/ProductVariant/33088239632427',
    shopify_store_domain: 'jarrow.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-bulksupplements-nr',
    product_name: 'Nicotinamide Riboside Capsules, Capsule / 120 Veg Capsules',
    product_description:
      'BulkSupplements nr pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 27.97,
    product_url: 'https://bulksupplements.com/products/nicotinamide-riboside-pills',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0114/8869/0276/files/Nicotinamide-Riboside-Veg-Capsules-120ct-Main-Image-V001.jpg?v=1762269187',
    servings_per_container: 120,
    servings_per_day: 1,
    brand_id: 'bulksupplements',
    brands: { brand_name: 'BulkSupplements' },
    supplement_name: 'NR',
    shopify_product_gid: 'gid://shopify/Product/8085332295874',
    shopify_variant_gid: 'gid://shopify/ProductVariant/45141635006658',
    shopify_store_domain: 'bulksupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-toniiq-spermidine',
    product_name: 'Spermidine 5MG',
    product_description:
      'Toniiq spermidine pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 44.41,
    product_url: 'https://toniiq.com/products/spermidine-11x',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0257/8723/files/Website_Image_Spermidine_5MG_120_Capsules_US.jpg?v=1732631122',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'toniiq',
    brands: { brand_name: 'Toniiq' },
    supplement_name: 'Spermidine',
    shopify_product_gid: 'gid://shopify/Product/7573772501206',
    shopify_variant_gid: 'gid://shopify/ProductVariant/42530887598294',
    shopify_store_domain: 'toniiq.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-jarrow-formulas-pqq',
    product_name: 'PQQ - 20mg, 30ct',
    product_description:
      'Jarrow Formulas pqq pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 31.99,
    product_url: 'https://jarrow.com/products/pqq-20-mg-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/2600/1286/files/PQ20_031623_Front.png?v=1687819998',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'jarrow-formulas',
    brands: { brand_name: 'Jarrow Formulas' },
    supplement_name: 'PQQ',
    shopify_product_gid: 'gid://shopify/Product/1389844299819',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40229815255083',
    shopify_store_domain: 'jarrow.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-horbaach-glucosamine',
    product_name: 'Glucosamine Sulfate 3000mg per serving',
    product_description:
      'Horbaach glucosamine pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 21.19,
    product_url: 'https://horbaach.com/products/glucosamine-sulfate-3000mg-per-serving-240-capsules-cl23',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0589/5336/7731/products/image-0_1deb8606-47d3-477e-836a-f769bd291a1d.png?v=1776762501',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'horbaach',
    brands: { brand_name: 'Horbaach' },
    supplement_name: 'Glucosamine',
    shopify_product_gid: 'gid://shopify/Product/7241961537715',
    shopify_variant_gid: 'gid://shopify/ProductVariant/41952712458419',
    shopify_store_domain: 'horbaach.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-purebulk-chondroitin',
    product_name: 'Chondroitin Sulfate, Bags / 100 grams',
    product_description:
      'PureBulk chondroitin pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 16.75,
    product_url: 'https://purebulk.com/products/chondroitin-sulfate',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0012/6379/6273/products/Chondroitin_Sulfate.jpg?v=1666903142',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'purebulk',
    brands: { brand_name: 'PureBulk' },
    supplement_name: 'Chondroitin',
    shopify_product_gid: 'gid://shopify/Product/1790130454577',
    shopify_variant_gid: 'gid://shopify/ProductVariant/14289077272625',
    shopify_store_domain: 'purebulk.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-bronson-msm',
    product_name: 'MSM High Potency - 1,000 mg - 250 Capsules',
    product_description:
      'Bronson msm pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 10.99,
    product_url: 'https://bronsonvitamins.com/products/msm-1000-mg-250-capsules',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0653/4489/7258/products/107b-0318-front.jpg?v=1674203164',
    servings_per_container: 250,
    servings_per_day: 1,
    brand_id: 'bronson',
    brands: { brand_name: 'Bronson' },
    supplement_name: 'MSM',
    shopify_product_gid: 'gid://shopify/Product/8051291783402',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44005332386026',
    shopify_store_domain: 'bronsonvitamins.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-nusapure-hyaluronic-acid',
    product_name: 'NusaPure Hyaluronic Acid 300mg 250 Veggie Capsules (Non-GMO, Vegan)',
    product_description:
      'NusaPure hyaluronic acid pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 30.49,
    product_url: 'https://nusapure.com/products/nusapure-hyaluronic-acid-300mg-250-veggie-capsules-non-gmo-vegan',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0978/6785/8240/files/112a91e5.jpg?v=1773759222',
    servings_per_container: 125,
    servings_per_day: 1,
    brand_id: 'nusapure',
    brands: { brand_name: 'NusaPure' },
    supplement_name: 'Hyaluronic Acid',
    shopify_product_gid: 'gid://shopify/Product/10073776881984',
    shopify_variant_gid: 'gid://shopify/ProductVariant/51628473614656',
    shopify_store_domain: 'nusapure.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-piping-rock-silica',
    product_name: 'Silica (Horsetail), 500 mg, 100 Quick Release Capsules',
    product_description:
      'Piping Rock silica pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 8.49,
    product_url: 'https://www.pipingrock.com/products/silica-horsetail-500-mg-100-quick-release-capsules-2141',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0640/7323/6718/files/silica-horsetail-500-mg-100-quick-release-capsules-2141.jpg?v=1782340696',
    servings_per_container: 100,
    servings_per_day: 1,
    brand_id: 'piping-rock',
    brands: { brand_name: 'Piping Rock' },
    supplement_name: 'Silica',
    shopify_product_gid: 'gid://shopify/Product/7782034735342',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43261431808238',
    shopify_store_domain: 'www.pipingrock.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-double-wood-keratin',
    product_name: 'Keratin Supplement, One Bottle',
    product_description:
      'Double Wood Supplements keratin pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 19.95,
    product_url: 'https://doublewoodsupplements.com/products/keratin',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0756/3867/files/Keratin_front_at2juc_6c97c46e-70e7-4728-a830-84debdb1ee6a.jpg?v=1769779494',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'double-wood',
    brands: { brand_name: 'Double Wood Supplements' },
    supplement_name: 'Keratin',
    shopify_product_gid: 'gid://shopify/Product/6890300014786',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44444551643330',
    shopify_store_domain: 'doublewoodsupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-bulksupplements-hemp-seed-oil',
    product_name: 'Hemp Seed Oil Softgels, Softgel / 240 Softgels',
    product_description:
      'BulkSupplements hemp seed oil pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 23.97,
    product_url: 'https://bulksupplements.com/products/hemp-seed-oil',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0114/8869/0276/files/Hemp-Seed-Oil-Softgels-240ct-Main-Image-V001.jpg?v=1762198699',
    servings_per_container: 240,
    servings_per_day: 1,
    brand_id: 'bulksupplements',
    brands: { brand_name: 'BulkSupplements' },
    supplement_name: 'Hemp Seed Oil',
    shopify_product_gid: 'gid://shopify/Product/7860313456834',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44294713934018',
    shopify_store_domain: 'bulksupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Softgels'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-purebulk-mct-oil',
    product_name: 'MCT Oil, 16oz',
    product_description:
      'PureBulk mct oil pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 12.5,
    product_url: 'https://purebulk.com/products/mct-oil-32oz',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0012/6379/6273/files/MCToil.avif?v=1782825666',
    servings_per_container: 32,
    servings_per_day: 1,
    brand_id: 'purebulk',
    brands: { brand_name: 'PureBulk' },
    supplement_name: 'MCT Oil',
    shopify_product_gid: 'gid://shopify/Product/4487900594225',
    shopify_variant_gid: 'gid://shopify/ProductVariant/45012927283397',
    shopify_store_domain: 'purebulk.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Liquid'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-zhou-nutrition-green-tea-extract',
    product_name: 'Green Tea Extract',
    product_description:
      'Zhou Nutrition green tea extract pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 23.09,
    product_url: 'https://zhounutrition.com/products/green-tea-extract',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0746/6555/files/GreenTea-1_1.png?v=1777566650',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'zhou-nutrition',
    brands: { brand_name: 'Zhou Nutrition' },
    supplement_name: 'Green Tea Extract',
    shopify_product_gid: 'gid://shopify/Product/1527013828',
    shopify_variant_gid: 'gid://shopify/ProductVariant/5959278985254',
    shopify_store_domain: 'zhounutrition.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-global-healing-quercetin',
    product_name: 'Quercetin, 60 Capsules',
    product_description:
      'Global Healing quercetin pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 37.95,
    product_url: 'https://globalhealing.com/products/quercetin',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0539/5621/4984/files/3000w_69317754-30d6-4a5e-9c42-d78c21946193.png?v=1762529055',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'global-healing',
    brands: { brand_name: 'Global Healing' },
    supplement_name: 'Quercetin',
    shopify_product_gid: 'gid://shopify/Product/6734056128712',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44403709149384',
    shopify_store_domain: 'globalhealing.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-maryruth-organics-elderberry',
    product_name: 'Organic Elderberry Liquid Drops',
    product_description:
      'MaryRuth Organics elderberry pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 19.95,
    product_url: 'https://maryruthorganics.com/products/organic-elderberry-liquid-drops',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0883/6750/files/1-organic-liquid-elderberry-drops-1oz-raspberry-blueberry-maryruths-bottle-box-benefits-shopify.png?v=1773344070',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'maryruth-organics',
    brands: { brand_name: 'MaryRuth Organics' },
    supplement_name: 'Elderberry',
    shopify_product_gid: 'gid://shopify/Product/2100410286177',
    shopify_variant_gid: 'gid://shopify/ProductVariant/39536973250657',
    shopify_store_domain: 'maryruthorganics.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Liquid'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-maryruth-organics-echinacea',
    product_name: 'Organic Echinacea Purpurea Herbal Liquid Drops',
    product_description:
      'MaryRuth Organics echinacea pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 21.95,
    product_url: 'https://maryruthorganics.com/products/organic-echinacea-purpurea-herbal-liquid-drops',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0883/6750/files/ORG_Echinacea_Drops_1oz_Unflavored.png?v=1772989741',
    servings_per_container: 30,
    servings_per_day: 1,
    brand_id: 'maryruth-organics',
    brands: { brand_name: 'MaryRuth Organics' },
    supplement_name: 'Echinacea',
    shopify_product_gid: 'gid://shopify/Product/6889149956193',
    shopify_variant_gid: 'gid://shopify/ProductVariant/40513327530081',
    shopify_store_domain: 'maryruthorganics.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Liquid'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-horbaach-reishi-mushroom',
    product_name: 'Reishi Mushroom',
    product_description:
      'Horbaach reishi mushroom pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 16.49,
    product_url: 'https://horbaach.com/products/reishi-mushroom-200-capsules-cl19652',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0589/5336/7731/files/image-0_6c0e66d1-8397-4b52-925f-a9d9be4e1065.png?v=1776762305',
    servings_per_container: 200,
    servings_per_day: 1,
    brand_id: 'horbaach',
    brands: { brand_name: 'Horbaach' },
    supplement_name: 'Reishi Mushroom',
    shopify_product_gid: 'gid://shopify/Product/7573552988339',
    shopify_variant_gid: 'gid://shopify/ProductVariant/42866705760435',
    shopify_store_domain: 'horbaach.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-piping-rock-cordyceps',
    product_name: 'Cordyceps Mushroom, 2000 mg (per serving), 200 Quick Release Capsules',
    product_description:
      'Piping Rock cordyceps pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 14.99,
    product_url: 'https://www.pipingrock.com/products/cordyceps-mushroom-2000-mg-per-serving-200-quick-release-capsules-16151',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0640/7323/6718/files/cordyceps-mushroom-2000-mg-per-serving-200-quick-release-capsules-16151.jpg?v=1782335058',
    servings_per_container: 200,
    servings_per_day: 1,
    brand_id: 'piping-rock',
    brands: { brand_name: 'Piping Rock' },
    supplement_name: 'Cordyceps',
    shopify_product_gid: 'gid://shopify/Product/7781987287278',
    shopify_variant_gid: 'gid://shopify/ProductVariant/43261359292654',
    shopify_store_domain: 'www.pipingrock.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
  {
    product_id: 'real-double-wood-chaga-mushroom',
    product_name: 'Chaga Mushroom Supplement, One Bottle',
    product_description:
      'Double Wood Supplements chaga mushroom pick with a verified merchant listing, so shoppers can move straight from the supplement page into secure cart checkout.',
    product_price: 19.95,
    product_url: 'https://doublewoodsupplements.com/products/chaga-mushroom',
    amazon_url: '',
    product_image: 'https://cdn.shopify.com/s/files/1/0756/3867/files/CHAGA_0004_2_02d9v3.jpg?v=1767119301',
    servings_per_container: 60,
    servings_per_day: 1,
    brand_id: 'double-wood',
    brands: { brand_name: 'Double Wood Supplements' },
    supplement_name: 'Chaga Mushroom',
    shopify_product_gid: 'gid://shopify/Product/7328317472962',
    shopify_variant_gid: 'gid://shopify/ProductVariant/44436015612098',
    shopify_store_domain: 'doublewoodsupplements.com',
    commerce_channel: 'shopify',
    ucp_enabled: true,
    inventory_status: 'in_stock',
    quality_badges: ['Verified merchant', 'Verified variant', 'Capsules'],
    subscriptions_available: false,
    data_source: 'shopify_ucp',
  },
];
